[package]
name = "showcase"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
garlic = { path = "..", version = "0.1.0" }
yew = { version = "0.20", features = ["csr"] }
